jobeet_backend_job:
    resource: "@JobeetBackendBundle/Resources/config/routing/job.yml"
    prefix:   /job

jobeet_backend_homepage:
    path:     /hello/{name}
    defaults: { _controller: JobeetBackendBundle:Default:index }
